--! Creating a new schema for storing final tables for ML
CREATE SCHEMA IF NOT EXISTS public_ready_for_ML;
--! Preparing TABLES
--* Merging train_data with incident_data
DROP TABLE IF EXISTS public_ready_for_ML.train_data;
CREATE TABLE IF NOT EXISTS public_ready_for_ML.train_data AS
SELECT train_data_final.*,
public_processed.station_data_final.*,
    type_incident,
    id_incident,
    dateH_incident,
    lieu,
    statut,
    statut_commercial,
    statut_financier,
    gravite,
    motif_client,
    commentaire,
    (
        tare_weight_0 + tare_weight_1 + tare_weight_2 + tare_weight_3 + tare_weight_4 + tare_weight_5 + tare_weight_6 + tare_weight_7 + tare_weight_8 + tare_weight_9 + tare_weight_10 + tare_weight_11 + tare_weight_12 + tare_weight_13 + tare_weight_14 + tare_weight_15 + tare_weight_16 + tare_weight_17 + tare_weight_18 + tare_weight_19 + tare_weight_20 + tare_weight_21 + tare_weight_22 + tare_weight_23 + tare_weight_24 + tare_weight_25 + tare_weight_26 + tare_weight_27 + tare_weight_28 + tare_weight_29 + tare_weight_30 + tare_weight_31 + tare_weight_32 + tare_weight_33 + tare_weight_34 + tare_weight_35
    ) AS train_tare_weight
FROM public_processed.train_data_final
    LEFT JOIN public_processed.incident_data ON public_processed.train_data_final.idtrain_lot = public_processed.incident_data.id_train_lot
LEFT JOIN public_processed.station_data_final ON public_processed.train_data_final.id_train = public_processed.station_data_final.id_train;
--! CREATING data related to trains and wagons
DROP TABLE IF EXISTS public_ready_for_ML.data1_trains_wagons;
CREATE TABLE IF NOT EXISTS public_ready_for_ML.data1_trains_wagons AS (
    SELECT id_train,
        lot_num_data_init,
        nom_lot_data_init,
        journey_distance,
        weight_co2,
        --idtrain_jalon_origin,
        --idtrain_jalon_destination,
        dateh_creation_data_init,
        dateh_maj_data_init,
        train_position_data_init,
        incoterm_data_init,
        TEU_Count,
        Max_TEU,
        train_weight,
        train_length,
        dateh_suppression_data_init,
        cancellation_reason,
        train_num_data_init,
        --id_relation_data_init,
        sens_data_init,
        max_weight,
        max_length,
        --id_train_parent_data_init,
        --id_train_etape_data_init,
        type_etape_data_init,
        dh_theorique_data_init,
        h_thorique_ecart_data_init,
        dh_reelle_data_init,
        dh_theorique_fin_data_init,
        dh_reelle_fin_data_init,
        cancelled_train_bin,
        wagon_count,
        train_distance_km,
        train_total_time_mins,
        train_travel_time_mins,
        train_idle_time_mins,
        travel_km_hr,
        total_km_hr,
        --idtrain_lot,
        idwagon_0,
        idwagon_1,
        idwagon_2,
        idwagon_3,
        idwagon_4,
        idwagon_5,
        idwagon_6,
        idwagon_7,
        idwagon_8,
        idwagon_9,
        idwagon_10,
        idwagon_11,
        idwagon_12,
        idwagon_13,
        idwagon_14,
        idwagon_15,
        idwagon_16,
        idwagon_17,
        idwagon_18,
        idwagon_19,
        idwagon_20,
        idwagon_21,
        idwagon_22,
        idwagon_23,
        idwagon_24,
        idwagon_25,
        idwagon_26,
        idwagon_27,
        idwagon_28,
        idwagon_29,
        idwagon_30,
        idwagon_31,
        idwagon_32,
        idwagon_33,
        idwagon_34,
        idwagon_35,
        modele_wagon_0,
        modele_wagon_1,
        modele_wagon_2,
        modele_wagon_3,
        modele_wagon_4,
        modele_wagon_5,
        modele_wagon_6,
        modele_wagon_7,
        modele_wagon_8,
        modele_wagon_9,
        modele_wagon_10,
        modele_wagon_11,
        modele_wagon_12,
        modele_wagon_13,
        modele_wagon_14,
        modele_wagon_15,
        modele_wagon_16,
        modele_wagon_17,
        modele_wagon_18,
        modele_wagon_19,
        modele_wagon_20,
        modele_wagon_21,
        modele_wagon_22,
        modele_wagon_23,
        modele_wagon_24,
        modele_wagon_25,
        modele_wagon_26,
        modele_wagon_27,
        modele_wagon_28,
        modele_wagon_29,
        modele_wagon_30,
        modele_wagon_31,
        modele_wagon_32,
        modele_wagon_33,
        modele_wagon_34,
        modele_wagon_35,
        wagon_type_0,
        wagon_type_1,
        wagon_type_2,
        wagon_type_3,
        wagon_type_4,
        wagon_type_5,
        wagon_type_6,
        wagon_type_7,
        wagon_type_8,
        wagon_type_9,
        wagon_type_10,
        wagon_type_11,
        wagon_type_12,
        wagon_type_13,
        wagon_type_14,
        wagon_type_15,
        wagon_type_16,
        wagon_type_17,
        wagon_type_18,
        wagon_type_19,
        wagon_type_20,
        wagon_type_21,
        wagon_type_22,
        wagon_type_23,
        wagon_type_24,
        wagon_type_25,
        wagon_type_26,
        wagon_type_27,
        wagon_type_28,
        wagon_type_29,
        wagon_type_30,
        wagon_type_31,
        wagon_type_32,
        wagon_type_33,
        wagon_type_34,
        wagon_type_35,
        max_speed_0,
        max_speed_1,
        max_speed_2,
        max_speed_3,
        max_speed_4,
        max_speed_5,
        max_speed_6,
        max_speed_7,
        max_speed_8,
        max_speed_9,
        max_speed_10,
        max_speed_11,
        max_speed_12,
        max_speed_13,
        max_speed_14,
        max_speed_15,
        max_speed_16,
        max_speed_17,
        max_speed_18,
        max_speed_19,
        max_speed_20,
        max_speed_21,
        max_speed_22,
        max_speed_23,
        max_speed_24,
        max_speed_25,
        max_speed_26,
        max_speed_27,
        max_speed_28,
        max_speed_29,
        max_speed_30,
        max_speed_31,
        max_speed_32,
        max_speed_33,
        max_speed_34,
        max_speed_35,
        wagon_model_tare_weight_0,
        wagon_model_tare_weight_1,
        wagon_model_tare_weight_2,
        wagon_model_tare_weight_3,
        wagon_model_tare_weight_4,
        wagon_model_tare_weight_5,
        wagon_model_tare_weight_6,
        wagon_model_tare_weight_7,
        wagon_model_tare_weight_8,
        wagon_model_tare_weight_9,
        wagon_model_tare_weight_10,
        wagon_model_tare_weight_11,
        wagon_model_tare_weight_12,
        wagon_model_tare_weight_13,
        wagon_model_tare_weight_14,
        wagon_model_tare_weight_15,
        wagon_model_tare_weight_16,
        wagon_model_tare_weight_17,
        wagon_model_tare_weight_18,
        wagon_model_tare_weight_19,
        wagon_model_tare_weight_20,
        wagon_model_tare_weight_21,
        wagon_model_tare_weight_22,
        wagon_model_tare_weight_23,
        wagon_model_tare_weight_24,
        wagon_model_tare_weight_25,
        wagon_model_tare_weight_26,
        wagon_model_tare_weight_27,
        wagon_model_tare_weight_28,
        wagon_model_tare_weight_29,
        wagon_model_tare_weight_30,
        wagon_model_tare_weight_31,
        wagon_model_tare_weight_32,
        wagon_model_tare_weight_33,
        wagon_model_tare_weight_34,
        wagon_model_tare_weight_35,
        tare_weight_0,
        tare_weight_1,
        tare_weight_2,
        tare_weight_3,
        tare_weight_4,
        tare_weight_5,
        tare_weight_6,
        tare_weight_7,
        tare_weight_8,
        tare_weight_9,
        tare_weight_10,
        tare_weight_11,
        tare_weight_12,
        tare_weight_13,
        tare_weight_14,
        tare_weight_15,
        tare_weight_16,
        tare_weight_17,
        tare_weight_18,
        tare_weight_19,
        tare_weight_20,
        tare_weight_21,
        tare_weight_22,
        tare_weight_23,
        tare_weight_24,
        tare_weight_25,
        tare_weight_26,
        tare_weight_27,
        tare_weight_28,
        tare_weight_29,
        tare_weight_30,
        tare_weight_31,
        tare_weight_32,
        tare_weight_33,
        tare_weight_34,
        tare_weight_35,
        wagon_start_date_0,
        wagon_start_date_1,
        wagon_start_date_2,
        wagon_start_date_3,
        wagon_start_date_4,
        wagon_start_date_5,
        wagon_start_date_6,
        wagon_start_date_7,
        wagon_start_date_8,
        wagon_start_date_9,
        wagon_start_date_10,
        wagon_start_date_11,
        wagon_start_date_12,
        wagon_start_date_13,
        wagon_start_date_14,
        wagon_start_date_15,
        wagon_start_date_16,
        wagon_start_date_17,
        wagon_start_date_18,
        wagon_start_date_19,
        wagon_start_date_20,
        wagon_start_date_21,
        wagon_start_date_22,
        wagon_start_date_23,
        wagon_start_date_24,
        wagon_start_date_25,
        wagon_start_date_26,
        wagon_start_date_27,
        wagon_start_date_28,
        wagon_start_date_29,
        wagon_start_date_30,
        wagon_start_date_31,
        wagon_start_date_32,
        wagon_start_date_33,
        wagon_start_date_34,
        wagon_start_date_35,
        type_incident,
        id_incident,
        dateh_incident,
        lieu,
        statut,
        statut_commercial,
        statut_financier,
        gravite,
        motif_client,
        commentaire,
        train_tare_weight
    FROM public_ready_for_ML.train_data
);
----------
SELECT *
FROM public_ready_for_ML.data1_trains_wagons
WHERE id_train = 7919;
--! CREATING data related to stations
DROP TABLE IF EXISTS public_ready_for_ML.data2_stations;
CREATE TABLE IF NOT EXISTS public_ready_for_ML.data2_stations AS (
    SELECT id_train,
        Station_Name_0 AS Station_Name_1_dep,
        Station_Name_1 AS Station_Name_1_arriv,
        Station_Name_2 AS Station_Name_2_dep,
        Station_Name_3 AS Station_Name_2_arriv,
        Station_Name_4 AS Station_Name_3_dep,
        Station_Name_5 AS Station_Name_3_arriv,
        Station_Name_6 AS Station_Name_4_dep,
        Station_Name_7 AS Station_Name_4_arriv,
        Station_Name_8 AS Station_Name_5_dep,
        Station_Name_9 AS Station_Name_5_arriv,
        Station_Name_10 AS Station_Name_6_dep,
        Station_Name_11 AS Station_Name_6_arriv,
        Station_Name_12 AS Station_Name_7_dep,
        Station_Name_13 AS Station_Name_7_arriv,
        Station_Name_14 AS Station_Name_8_dep,
        Station_Name_15 AS Station_Name_8_arriv,
        Station_Name_16 AS Station_Name_9_dep,
        Station_Name_17 AS Station_Name_9_arriv,
        Station_Name_18 AS Station_Name_10_dep,
        Station_Name_19 AS Station_Name_10_arriv,
        Station_Name_20 AS Station_Name_11_dep,
        Station_Name_21 AS Station_Name_11_arriv,
        Station_Name_22 AS Station_Name_12_dep,
        Station_Name_23 AS Station_Name_12_arriv,
        Plan_Timestamp_0 AS Plan_Timestamp_1_dep,
        Plan_Timestamp_1 AS Plan_Timestamp_1_arriv,
        Plan_Timestamp_2 AS Plan_Timestamp_2_dep,
        Plan_Timestamp_3 AS Plan_Timestamp_2_arriv,
        Plan_Timestamp_4 AS Plan_Timestamp_3_dep,
        Plan_Timestamp_5 AS Plan_Timestamp_3_arriv,
        Plan_Timestamp_6 AS Plan_Timestamp_4_dep,
        Plan_Timestamp_7 AS Plan_Timestamp_4_arriv,
        Plan_Timestamp_8 AS Plan_Timestamp_5_dep,
        Plan_Timestamp_9 AS Plan_Timestamp_5_arriv,
        Plan_Timestamp_10 AS Plan_Timestamp_6_dep,
        Plan_Timestamp_11 AS Plan_Timestamp_6_arriv,
        Plan_Timestamp_12 AS Plan_Timestamp_7_dep,
        Plan_Timestamp_13 AS Plan_Timestamp_7_arriv,
        Plan_Timestamp_14 AS Plan_Timestamp_8_dep,
        Plan_Timestamp_15 AS Plan_Timestamp_8_arriv,
        Plan_Timestamp_16 AS Plan_Timestamp_9_dep,
        Plan_Timestamp_17 AS Plan_Timestamp_9_arriv,
        Plan_Timestamp_18 AS Plan_Timestamp_10_dep,
        Plan_Timestamp_19 AS Plan_Timestamp_10_arriv,
        Plan_Timestamp_20 AS Plan_Timestamp_11_dep,
        Plan_Timestamp_21 AS Plan_Timestamp_11_arriv,
        Plan_Timestamp_22 AS Plan_Timestamp_12_dep,
        Plan_Timestamp_23 AS Plan_Timestamp_12_arriv,
        Actual_Timestamp_0 AS Actual_Timestamp_1_dep,
        Actual_Timestamp_1 AS Actual_Timestamp_1_arriv,
        Actual_Timestamp_2 AS Actual_Timestamp_2_dep,
        Actual_Timestamp_3 AS Actual_Timestamp_2_arriv,
        Actual_Timestamp_4 AS Actual_Timestamp_3_dep,
        Actual_Timestamp_5 AS Actual_Timestamp_3_arriv,
        Actual_Timestamp_6 AS Actual_Timestamp_4_dep,
        Actual_Timestamp_7 AS Actual_Timestamp_4_arriv,
        Actual_Timestamp_8 AS Actual_Timestamp_5_dep,
        Actual_Timestamp_9 AS Actual_Timestamp_5_arriv,
        Actual_Timestamp_10 AS Actual_Timestamp_6_dep,
        Actual_Timestamp_11 AS Actual_Timestamp_6_arriv,
        Actual_Timestamp_12 AS Actual_Timestamp_7_dep,
        Actual_Timestamp_13 AS Actual_Timestamp_7_arriv,
        Actual_Timestamp_14 AS Actual_Timestamp_8_dep,
        Actual_Timestamp_15 AS Actual_Timestamp_8_arriv,
        Actual_Timestamp_16 AS Actual_Timestamp_9_dep,
        Actual_Timestamp_17 AS Actual_Timestamp_9_arriv,
        Actual_Timestamp_18 AS Actual_Timestamp_10_dep,
        Actual_Timestamp_19 AS Actual_Timestamp_10_arriv,
        Actual_Timestamp_20 AS Actual_Timestamp_11_dep,
        Actual_Timestamp_21 AS Actual_Timestamp_11_arriv,
        Actual_Timestamp_22 AS Actual_Timestamp_12_dep,
        Actual_Timestamp_23 AS Actual_Timestamp_12_arriv,
        Time_From_Prior_Plan_Mins_0 AS Time_From_Prior_Plan_Mins_1_dep,
        Time_From_Prior_Plan_Mins_1 AS Time_From_Prior_Plan_Mins_1_arriv,
        Time_From_Prior_Plan_Mins_2 AS Time_From_Prior_Plan_Mins_2_dep,
        Time_From_Prior_Plan_Mins_3 AS Time_From_Prior_Plan_Mins_2_arriv,
        Time_From_Prior_Plan_Mins_4 AS Time_From_Prior_Plan_Mins_3_dep,
        Time_From_Prior_Plan_Mins_5 AS Time_From_Prior_Plan_Mins_3_arriv,
        Time_From_Prior_Plan_Mins_6 AS Time_From_Prior_Plan_Mins_4_dep,
        Time_From_Prior_Plan_Mins_7 AS Time_From_Prior_Plan_Mins_4_arriv,
        Time_From_Prior_Plan_Mins_8 AS Time_From_Prior_Plan_Mins_5_dep,
        Time_From_Prior_Plan_Mins_9 AS Time_From_Prior_Plan_Mins_5_arriv,
        Time_From_Prior_Plan_Mins_10 AS Time_From_Prior_Plan_Mins_6_dep,
        Time_From_Prior_Plan_Mins_11 AS Time_From_Prior_Plan_Mins_6_arriv,
        Time_From_Prior_Plan_Mins_12 AS Time_From_Prior_Plan_Mins_7_dep,
        Time_From_Prior_Plan_Mins_13 AS Time_From_Prior_Plan_Mins_7_arriv,
        Time_From_Prior_Plan_Mins_14 AS Time_From_Prior_Plan_Mins_8_dep,
        Time_From_Prior_Plan_Mins_15 AS Time_From_Prior_Plan_Mins_8_arriv,
        Time_From_Prior_Plan_Mins_16 AS Time_From_Prior_Plan_Mins_9_dep,
        Time_From_Prior_Plan_Mins_17 AS Time_From_Prior_Plan_Mins_9_arriv,
        Time_From_Prior_Plan_Mins_18 AS Time_From_Prior_Plan_Mins_10_dep,
        Time_From_Prior_Plan_Mins_19 AS Time_From_Prior_Plan_Mins_10_arriv,
        Time_From_Prior_Plan_Mins_20 AS Time_From_Prior_Plan_Mins_11_dep,
        Time_From_Prior_Plan_Mins_21 AS Time_From_Prior_Plan_Mins_11_arriv,
        Time_From_Prior_Plan_Mins_22 AS Time_From_Prior_Plan_Mins_12_dep,
        Time_From_Prior_Plan_Mins_23 AS Time_From_Prior_Plan_Mins_12_arriv,
        Depart_Variance_Mins_0 AS Depart_Variance_Mins_1_dep,
        Depart_Variance_Mins_1 AS Depart_Variance_Mins_1_arriv,
        Depart_Variance_Mins_2 AS Depart_Variance_Mins_2_dep,
        Depart_Variance_Mins_3 AS Depart_Variance_Mins_2_arriv,
        Depart_Variance_Mins_4 AS Depart_Variance_Mins_3_dep,
        Depart_Variance_Mins_5 AS Depart_Variance_Mins_3_arriv,
        Depart_Variance_Mins_6 AS Depart_Variance_Mins_4_dep,
        Depart_Variance_Mins_7 AS Depart_Variance_Mins_4_arriv,
        Depart_Variance_Mins_8 AS Depart_Variance_Mins_5_dep,
        Depart_Variance_Mins_9 AS Depart_Variance_Mins_5_arriv,
        Depart_Variance_Mins_10 AS Depart_Variance_Mins_6_dep,
        Depart_Variance_Mins_11 AS Depart_Variance_Mins_6_arriv,
        Depart_Variance_Mins_12 AS Depart_Variance_Mins_7_dep,
        Depart_Variance_Mins_13 AS Depart_Variance_Mins_7_arriv,
        Depart_Variance_Mins_14 AS Depart_Variance_Mins_8_dep,
        Depart_Variance_Mins_15 AS Depart_Variance_Mins_8_arriv,
        Depart_Variance_Mins_16 AS Depart_Variance_Mins_9_dep,
        Depart_Variance_Mins_17 AS Depart_Variance_Mins_9_arriv,
        Depart_Variance_Mins_18 AS Depart_Variance_Mins_10_dep,
        Depart_Variance_Mins_19 AS Depart_Variance_Mins_10_arriv,
        Depart_Variance_Mins_20 AS Depart_Variance_Mins_11_dep,
        Depart_Variance_Mins_21 AS Depart_Variance_Mins_11_arriv,
        Depart_Variance_Mins_22 AS Depart_Variance_Mins_12_dep,
        Depart_Variance_Mins_23 AS Depart_Variance_Mins_12_arriv,
        Arrive_Variance_Mins_0 AS Arrive_Variance_Mins_1_dep,
        Arrive_Variance_Mins_1 AS Arrive_Variance_Mins_1_arriv,
        Arrive_Variance_Mins_2 AS Arrive_Variance_Mins_2_dep,
        Arrive_Variance_Mins_3 AS Arrive_Variance_Mins_2_arriv,
        Arrive_Variance_Mins_4 AS Arrive_Variance_Mins_3_dep,
        Arrive_Variance_Mins_5 AS Arrive_Variance_Mins_3_arriv,
        Arrive_Variance_Mins_6 AS Arrive_Variance_Mins_4_dep,
        Arrive_Variance_Mins_7 AS Arrive_Variance_Mins_4_arriv,
        Arrive_Variance_Mins_8 AS Arrive_Variance_Mins_5_dep,
        Arrive_Variance_Mins_9 AS Arrive_Variance_Mins_5_arriv,
        Arrive_Variance_Mins_10 AS Arrive_Variance_Mins_6_dep,
        Arrive_Variance_Mins_11 AS Arrive_Variance_Mins_6_arriv,
        Arrive_Variance_Mins_12 AS Arrive_Variance_Mins_7_dep,
        Arrive_Variance_Mins_13 AS Arrive_Variance_Mins_7_arriv,
        Arrive_Variance_Mins_14 AS Arrive_Variance_Mins_8_dep,
        Arrive_Variance_Mins_15 AS Arrive_Variance_Mins_8_arriv,
        Arrive_Variance_Mins_16 AS Arrive_Variance_Mins_9_dep,
        Arrive_Variance_Mins_17 AS Arrive_Variance_Mins_9_arriv,
        Arrive_Variance_Mins_18 AS Arrive_Variance_Mins_10_dep,
        Arrive_Variance_Mins_19 AS Arrive_Variance_Mins_10_arriv,
        Arrive_Variance_Mins_20 AS Arrive_Variance_Mins_11_dep,
        Arrive_Variance_Mins_21 AS Arrive_Variance_Mins_11_arriv,
        Arrive_Variance_Mins_22 AS Arrive_Variance_Mins_12_dep,
        Arrive_Variance_Mins_23 AS Arrive_Variance_Mins_12_arriv,
        Travel_Time_Mins_0 AS Travel_Time_Mins_1_dep,
        Travel_Time_Mins_1 AS Travel_Time_Mins_1_arriv,
        Travel_Time_Mins_2 AS Travel_Time_Mins_2_dep,
        Travel_Time_Mins_3 AS Travel_Time_Mins_2_arriv,
        Travel_Time_Mins_4 AS Travel_Time_Mins_3_dep,
        Travel_Time_Mins_5 AS Travel_Time_Mins_3_arriv,
        Travel_Time_Mins_6 AS Travel_Time_Mins_4_dep,
        Travel_Time_Mins_7 AS Travel_Time_Mins_4_arriv,
        Travel_Time_Mins_8 AS Travel_Time_Mins_5_dep,
        Travel_Time_Mins_9 AS Travel_Time_Mins_5_arriv,
        Travel_Time_Mins_10 AS Travel_Time_Mins_6_dep,
        Travel_Time_Mins_11 AS Travel_Time_Mins_6_arriv,
        Travel_Time_Mins_12 AS Travel_Time_Mins_7_dep,
        Travel_Time_Mins_13 AS Travel_Time_Mins_7_arriv,
        Travel_Time_Mins_14 AS Travel_Time_Mins_8_dep,
        Travel_Time_Mins_15 AS Travel_Time_Mins_8_arriv,
        Travel_Time_Mins_16 AS Travel_Time_Mins_9_dep,
        Travel_Time_Mins_17 AS Travel_Time_Mins_9_arriv,
        Travel_Time_Mins_18 AS Travel_Time_Mins_10_dep,
        Travel_Time_Mins_19 AS Travel_Time_Mins_10_arriv,
        Travel_Time_Mins_20 AS Travel_Time_Mins_11_dep,
        Travel_Time_Mins_21 AS Travel_Time_Mins_11_arriv,
        Travel_Time_Mins_22 AS Travel_Time_Mins_12_dep,
        Travel_Time_Mins_23 AS Travel_Time_Mins_12_arriv,
        Idle_Time_Mins_0 AS Idle_Time_Mins_1_dep,
        Idle_Time_Mins_1 AS Idle_Time_Mins_1_arriv,
        Idle_Time_Mins_2 AS Idle_Time_Mins_2_dep,
        Idle_Time_Mins_3 AS Idle_Time_Mins_2_arriv,
        Idle_Time_Mins_4 AS Idle_Time_Mins_3_dep,
        Idle_Time_Mins_5 AS Idle_Time_Mins_3_arriv,
        Idle_Time_Mins_6 AS Idle_Time_Mins_4_dep,
        Idle_Time_Mins_7 AS Idle_Time_Mins_4_arriv,
        Idle_Time_Mins_8 AS Idle_Time_Mins_5_dep,
        Idle_Time_Mins_9 AS Idle_Time_Mins_5_arriv,
        Idle_Time_Mins_10 AS Idle_Time_Mins_6_dep,
        Idle_Time_Mins_11 AS Idle_Time_Mins_6_arriv,
        Idle_Time_Mins_12 AS Idle_Time_Mins_7_dep,
        Idle_Time_Mins_13 AS Idle_Time_Mins_7_arriv,
        Idle_Time_Mins_14 AS Idle_Time_Mins_8_dep,
        Idle_Time_Mins_15 AS Idle_Time_Mins_8_arriv,
        Idle_Time_Mins_16 AS Idle_Time_Mins_9_dep,
        Idle_Time_Mins_17 AS Idle_Time_Mins_9_arriv,
        Idle_Time_Mins_18 AS Idle_Time_Mins_10_dep,
        Idle_Time_Mins_19 AS Idle_Time_Mins_10_arriv,
        Idle_Time_Mins_20 AS Idle_Time_Mins_11_dep,
        Idle_Time_Mins_21 AS Idle_Time_Mins_11_arriv,
        Idle_Time_Mins_22 AS Idle_Time_Mins_12_dep,
        Idle_Time_Mins_23 AS Idle_Time_Mins_12_arriv,
        KM_Distance_Event_0 AS KM_Distance_Event_1_dep,
        KM_Distance_Event_1 AS KM_Distance_Event_1_arriv,
        KM_Distance_Event_2 AS KM_Distance_Event_2_dep,
        KM_Distance_Event_3 AS KM_Distance_Event_2_arriv,
        KM_Distance_Event_4 AS KM_Distance_Event_3_dep,
        KM_Distance_Event_5 AS KM_Distance_Event_3_arriv,
        KM_Distance_Event_6 AS KM_Distance_Event_4_dep,
        KM_Distance_Event_7 AS KM_Distance_Event_4_arriv,
        KM_Distance_Event_8 AS KM_Distance_Event_5_dep,
        KM_Distance_Event_9 AS KM_Distance_Event_5_arriv,
        KM_Distance_Event_10 AS KM_Distance_Event_6_dep,
        KM_Distance_Event_11 AS KM_Distance_Event_6_arriv,
        KM_Distance_Event_12 AS KM_Distance_Event_7_dep,
        KM_Distance_Event_13 AS KM_Distance_Event_7_arriv,
        KM_Distance_Event_14 AS KM_Distance_Event_8_dep,
        KM_Distance_Event_15 AS KM_Distance_Event_8_arriv,
        KM_Distance_Event_16 AS KM_Distance_Event_9_dep,
        KM_Distance_Event_17 AS KM_Distance_Event_9_arriv,
        KM_Distance_Event_18 AS KM_Distance_Event_10_dep,
        KM_Distance_Event_19 AS KM_Distance_Event_10_arriv,
        KM_Distance_Event_20 AS KM_Distance_Event_11_dep,
        KM_Distance_Event_21 AS KM_Distance_Event_11_arriv,
        KM_Distance_Event_22 AS KM_Distance_Event_12_dep,
        KM_Distance_Event_23 AS KM_Distance_Event_12_arriv,
        KM_HR_Event_0 AS KM_HR_Event_1_dep,
        KM_HR_Event_1 AS KM_HR_Event_1_arriv,
        KM_HR_Event_2 AS KM_HR_Event_2_dep,
        KM_HR_Event_3 AS KM_HR_Event_2_arriv,
        KM_HR_Event_4 AS KM_HR_Event_3_dep,
        KM_HR_Event_5 AS KM_HR_Event_3_arriv,
        KM_HR_Event_6 AS KM_HR_Event_4_dep,
        KM_HR_Event_7 AS KM_HR_Event_4_arriv,
        KM_HR_Event_8 AS KM_HR_Event_5_dep,
        KM_HR_Event_9 AS KM_HR_Event_5_arriv,
        KM_HR_Event_10 AS KM_HR_Event_6_dep,
        KM_HR_Event_11 AS KM_HR_Event_6_arriv,
        KM_HR_Event_12 AS KM_HR_Event_7_dep,
        KM_HR_Event_13 AS KM_HR_Event_7_arriv,
        KM_HR_Event_14 AS KM_HR_Event_8_dep,
        KM_HR_Event_15 AS KM_HR_Event_8_arriv,
        KM_HR_Event_16 AS KM_HR_Event_9_dep,
        KM_HR_Event_17 AS KM_HR_Event_9_arriv,
        KM_HR_Event_18 AS KM_HR_Event_10_dep,
        KM_HR_Event_19 AS KM_HR_Event_10_arriv,
        KM_HR_Event_20 AS KM_HR_Event_11_dep,
        KM_HR_Event_21 AS KM_HR_Event_11_arriv,
        KM_HR_Event_22 AS KM_HR_Event_12_dep,
        KM_HR_Event_23 AS KM_HR_Event_12_arriv
    FROM public_ready_for_ML.train_data
);
--! CREATING data_final
DROP TABLE IF EXISTS public_ready_for_ML.df_final_for_ml;
CREATE TABLE IF NOT EXISTS public_ready_for_ML.df_final_for_ml AS WITH data_station_1 AS (
    SELECT id_train,
        Station_Name_1_dep AS Station_Name_dep,
        Station_Name_1_arriv AS Station_Name_arriv,
        Plan_Timestamp_1_dep AS Plan_Timestamp_dep,
        Plan_Timestamp_1_arriv AS Plan_Timestamp_arriv,
        Actual_Timestamp_1_dep AS Actual_Timestamp_dep,
        Actual_Timestamp_1_arriv AS Actual_Timestamp_arriv,
        Time_From_Prior_Plan_Mins_1_dep AS Time_From_Prior_Plan_Mins_dep,
        Time_From_Prior_Plan_Mins_1_arriv AS Time_From_Prior_Plan_Mins_arriv,
        Depart_Variance_Mins_1_dep AS Depart_Variance_Mins_dep,
        Depart_Variance_Mins_1_arriv AS Depart_Variance_Mins_arriv,
        Arrive_Variance_Mins_1_dep AS Arrive_Variance_Mins_dep,
        Arrive_Variance_Mins_1_arriv AS Arrive_Variance_Mins_arriv,
        Travel_Time_Mins_1_dep AS Travel_Time_Mins_dep,
        Travel_Time_Mins_1_arriv AS Travel_Time_Mins_arriv,
        Idle_Time_Mins_1_dep AS Idle_Time_Mins_dep,
        Idle_Time_Mins_1_arriv AS Idle_Time_Mins_arriv,
        KM_Distance_Event_1_dep AS KM_Distance_Event_dep,
        KM_Distance_Event_1_arriv AS KM_Distance_Event_arriv,
        KM_HR_Event_1_dep AS KM_HR_Event_dep,
        KM_HR_Event_1_arriv AS KM_HR_Event_arriv
    FROM public_ready_for_ML.data2_stations
),
data_station_2 AS (
    SELECT id_train,
        Station_Name_2_dep AS Station_Name_dep,
        Station_Name_2_arriv AS Station_Name_arriv,
        Plan_Timestamp_2_dep AS Plan_Timestamp_dep,
        Plan_Timestamp_2_arriv AS Plan_Timestamp_arriv,
        Actual_Timestamp_2_dep AS Actual_Timestamp_dep,
        Actual_Timestamp_2_arriv AS Actual_Timestamp_arriv,
        Time_From_Prior_Plan_Mins_2_dep AS Time_From_Prior_Plan_Mins_dep,
        Time_From_Prior_Plan_Mins_2_arriv AS Time_From_Prior_Plan_Mins_arriv,
        Depart_Variance_Mins_2_dep AS Depart_Variance_Mins_dep,
        Depart_Variance_Mins_2_arriv AS Depart_Variance_Mins_arriv,
        Arrive_Variance_Mins_2_dep AS Arrive_Variance_Mins_dep,
        Arrive_Variance_Mins_2_arriv AS Arrive_Variance_Mins_arriv,
        Travel_Time_Mins_2_dep AS Travel_Time_Mins_dep,
        Travel_Time_Mins_2_arriv AS Travel_Time_Mins_arriv,
        Idle_Time_Mins_2_dep AS Idle_Time_Mins_dep,
        Idle_Time_Mins_2_arriv AS Idle_Time_Mins_arriv,
        KM_Distance_Event_2_dep AS KM_Distance_Event_dep,
        KM_Distance_Event_2_arriv AS KM_Distance_Event_arriv,
        KM_HR_Event_2_dep AS KM_HR_Event_dep,
        KM_HR_Event_2_arriv AS KM_HR_Event_arriv
    FROM public_ready_for_ML.data2_stations
),
data_station_3 AS (
    SELECT id_train,
        Station_Name_3_dep AS Station_Name_dep,
        Station_Name_3_arriv AS Station_Name_arriv,
        Plan_Timestamp_3_dep AS Plan_Timestamp_dep,
        Plan_Timestamp_3_arriv AS Plan_Timestamp_arriv,
        Actual_Timestamp_3_dep AS Actual_Timestamp_dep,
        Actual_Timestamp_3_arriv AS Actual_Timestamp_arriv,
        Time_From_Prior_Plan_Mins_3_dep AS Time_From_Prior_Plan_Mins_dep,
        Time_From_Prior_Plan_Mins_3_arriv AS Time_From_Prior_Plan_Mins_arriv,
        Depart_Variance_Mins_3_dep AS Depart_Variance_Mins_dep,
        Depart_Variance_Mins_3_arriv AS Depart_Variance_Mins_arriv,
        Arrive_Variance_Mins_3_dep AS Arrive_Variance_Mins_dep,
        Arrive_Variance_Mins_3_arriv AS Arrive_Variance_Mins_arriv,
        Travel_Time_Mins_3_dep AS Travel_Time_Mins_dep,
        Travel_Time_Mins_3_arriv AS Travel_Time_Mins_arriv,
        Idle_Time_Mins_3_dep AS Idle_Time_Mins_dep,
        Idle_Time_Mins_3_arriv AS Idle_Time_Mins_arriv,
        KM_Distance_Event_3_dep AS KM_Distance_Event_dep,
        KM_Distance_Event_3_arriv AS KM_Distance_Event_arriv,
        KM_HR_Event_3_dep AS KM_HR_Event_dep,
        KM_HR_Event_3_arriv AS KM_HR_Event_arriv
    FROM public_ready_for_ML.data2_stations
),
data_station_4 AS (
    SELECT id_train,
        Station_Name_4_dep AS Station_Name_dep,
        Station_Name_4_arriv AS Station_Name_arriv,
        Plan_Timestamp_4_dep AS Plan_Timestamp_dep,
        Plan_Timestamp_4_arriv AS Plan_Timestamp_arriv,
        Actual_Timestamp_4_dep AS Actual_Timestamp_dep,
        Actual_Timestamp_4_arriv AS Actual_Timestamp_arriv,
        Time_From_Prior_Plan_Mins_4_dep AS Time_From_Prior_Plan_Mins_dep,
        Time_From_Prior_Plan_Mins_4_arriv AS Time_From_Prior_Plan_Mins_arriv,
        Depart_Variance_Mins_4_dep AS Depart_Variance_Mins_dep,
        Depart_Variance_Mins_4_arriv AS Depart_Variance_Mins_arriv,
        Arrive_Variance_Mins_4_dep AS Arrive_Variance_Mins_dep,
        Arrive_Variance_Mins_4_arriv AS Arrive_Variance_Mins_arriv,
        Travel_Time_Mins_4_dep AS Travel_Time_Mins_dep,
        Travel_Time_Mins_4_arriv AS Travel_Time_Mins_arriv,
        Idle_Time_Mins_4_dep AS Idle_Time_Mins_dep,
        Idle_Time_Mins_4_arriv AS Idle_Time_Mins_arriv,
        KM_Distance_Event_4_dep AS KM_Distance_Event_dep,
        KM_Distance_Event_4_arriv AS KM_Distance_Event_arriv,
        KM_HR_Event_4_dep AS KM_HR_Event_dep,
        KM_HR_Event_4_arriv AS KM_HR_Event_arriv
    FROM public_ready_for_ML.data2_stations
),
data_station_5 AS (
    SELECT id_train,
        Station_Name_5_dep AS Station_Name_dep,
        Station_Name_5_arriv AS Station_Name_arriv,
        Plan_Timestamp_5_dep AS Plan_Timestamp_dep,
        Plan_Timestamp_5_arriv AS Plan_Timestamp_arriv,
        Actual_Timestamp_5_dep AS Actual_Timestamp_dep,
        Actual_Timestamp_5_arriv AS Actual_Timestamp_arriv,
        Time_From_Prior_Plan_Mins_5_dep AS Time_From_Prior_Plan_Mins_dep,
        Time_From_Prior_Plan_Mins_5_arriv AS Time_From_Prior_Plan_Mins_arriv,
        Depart_Variance_Mins_5_dep AS Depart_Variance_Mins_dep,
        Depart_Variance_Mins_5_arriv AS Depart_Variance_Mins_arriv,
        Arrive_Variance_Mins_5_dep AS Arrive_Variance_Mins_dep,
        Arrive_Variance_Mins_5_arriv AS Arrive_Variance_Mins_arriv,
        Travel_Time_Mins_5_dep AS Travel_Time_Mins_dep,
        Travel_Time_Mins_5_arriv AS Travel_Time_Mins_arriv,
        Idle_Time_Mins_5_dep AS Idle_Time_Mins_dep,
        Idle_Time_Mins_5_arriv AS Idle_Time_Mins_arriv,
        KM_Distance_Event_5_dep AS KM_Distance_Event_dep,
        KM_Distance_Event_5_arriv AS KM_Distance_Event_arriv,
        KM_HR_Event_5_dep AS KM_HR_Event_dep,
        KM_HR_Event_5_arriv AS KM_HR_Event_arriv
    FROM public_ready_for_ML.data2_stations
),
data_station_6 AS (
    SELECT id_train,
        Station_Name_6_dep AS Station_Name_dep,
        Station_Name_6_arriv AS Station_Name_arriv,
        Plan_Timestamp_6_dep AS Plan_Timestamp_dep,
        Plan_Timestamp_6_arriv AS Plan_Timestamp_arriv,
        Actual_Timestamp_6_dep AS Actual_Timestamp_dep,
        Actual_Timestamp_6_arriv AS Actual_Timestamp_arriv,
        Time_From_Prior_Plan_Mins_6_dep AS Time_From_Prior_Plan_Mins_dep,
        Time_From_Prior_Plan_Mins_6_arriv AS Time_From_Prior_Plan_Mins_arriv,
        Depart_Variance_Mins_6_dep AS Depart_Variance_Mins_dep,
        Depart_Variance_Mins_6_arriv AS Depart_Variance_Mins_arriv,
        Arrive_Variance_Mins_6_dep AS Arrive_Variance_Mins_dep,
        Arrive_Variance_Mins_6_arriv AS Arrive_Variance_Mins_arriv,
        Travel_Time_Mins_6_dep AS Travel_Time_Mins_dep,
        Travel_Time_Mins_6_arriv AS Travel_Time_Mins_arriv,
        Idle_Time_Mins_6_dep AS Idle_Time_Mins_dep,
        Idle_Time_Mins_6_arriv AS Idle_Time_Mins_arriv,
        KM_Distance_Event_6_dep AS KM_Distance_Event_dep,
        KM_Distance_Event_6_arriv AS KM_Distance_Event_arriv,
        KM_HR_Event_6_dep AS KM_HR_Event_dep,
        KM_HR_Event_6_arriv AS KM_HR_Event_arriv
    FROM public_ready_for_ML.data2_stations
),
data_station_7 AS (
    SELECT id_train,
        Station_Name_7_dep AS Station_Name_dep,
        Station_Name_7_arriv AS Station_Name_arriv,
        Plan_Timestamp_7_dep AS Plan_Timestamp_dep,
        Plan_Timestamp_7_arriv AS Plan_Timestamp_arriv,
        Actual_Timestamp_7_dep AS Actual_Timestamp_dep,
        Actual_Timestamp_7_arriv AS Actual_Timestamp_arriv,
        Time_From_Prior_Plan_Mins_7_dep AS Time_From_Prior_Plan_Mins_dep,
        Time_From_Prior_Plan_Mins_7_arriv AS Time_From_Prior_Plan_Mins_arriv,
        Depart_Variance_Mins_7_dep AS Depart_Variance_Mins_dep,
        Depart_Variance_Mins_7_arriv AS Depart_Variance_Mins_arriv,
        Arrive_Variance_Mins_7_dep AS Arrive_Variance_Mins_dep,
        Arrive_Variance_Mins_7_arriv AS Arrive_Variance_Mins_arriv,
        Travel_Time_Mins_7_dep AS Travel_Time_Mins_dep,
        Travel_Time_Mins_7_arriv AS Travel_Time_Mins_arriv,
        Idle_Time_Mins_7_dep AS Idle_Time_Mins_dep,
        Idle_Time_Mins_7_arriv AS Idle_Time_Mins_arriv,
        KM_Distance_Event_7_dep AS KM_Distance_Event_dep,
        KM_Distance_Event_7_arriv AS KM_Distance_Event_arriv,
        KM_HR_Event_7_dep AS KM_HR_Event_dep,
        KM_HR_Event_7_arriv AS KM_HR_Event_arriv
    FROM public_ready_for_ML.data2_stations
),
data_station_8 AS (
    SELECT id_train,
        Station_Name_8_dep AS Station_Name_dep,
        Station_Name_8_arriv AS Station_Name_arriv,
        Plan_Timestamp_8_dep AS Plan_Timestamp_dep,
        Plan_Timestamp_8_arriv AS Plan_Timestamp_arriv,
        Actual_Timestamp_8_dep AS Actual_Timestamp_dep,
        Actual_Timestamp_8_arriv AS Actual_Timestamp_arriv,
        Time_From_Prior_Plan_Mins_8_dep AS Time_From_Prior_Plan_Mins_dep,
        Time_From_Prior_Plan_Mins_8_arriv AS Time_From_Prior_Plan_Mins_arriv,
        Depart_Variance_Mins_8_dep AS Depart_Variance_Mins_dep,
        Depart_Variance_Mins_8_arriv AS Depart_Variance_Mins_arriv,
        Arrive_Variance_Mins_8_dep AS Arrive_Variance_Mins_dep,
        Arrive_Variance_Mins_8_arriv AS Arrive_Variance_Mins_arriv,
        Travel_Time_Mins_8_dep AS Travel_Time_Mins_dep,
        Travel_Time_Mins_8_arriv AS Travel_Time_Mins_arriv,
        Idle_Time_Mins_8_dep AS Idle_Time_Mins_dep,
        Idle_Time_Mins_8_arriv AS Idle_Time_Mins_arriv,
        KM_Distance_Event_8_dep AS KM_Distance_Event_dep,
        KM_Distance_Event_8_arriv AS KM_Distance_Event_arriv,
        KM_HR_Event_8_dep AS KM_HR_Event_dep,
        KM_HR_Event_8_arriv AS KM_HR_Event_arriv
    FROM public_ready_for_ML.data2_stations
),
data_station_9 AS (
    SELECT id_train,
        Station_Name_9_dep AS Station_Name_dep,
        Station_Name_9_arriv AS Station_Name_arriv,
        Plan_Timestamp_9_dep AS Plan_Timestamp_dep,
        Plan_Timestamp_9_arriv AS Plan_Timestamp_arriv,
        Actual_Timestamp_9_dep AS Actual_Timestamp_dep,
        Actual_Timestamp_9_arriv AS Actual_Timestamp_arriv,
        Time_From_Prior_Plan_Mins_9_dep AS Time_From_Prior_Plan_Mins_dep,
        Time_From_Prior_Plan_Mins_9_arriv AS Time_From_Prior_Plan_Mins_arriv,
        Depart_Variance_Mins_9_dep AS Depart_Variance_Mins_dep,
        Depart_Variance_Mins_9_arriv AS Depart_Variance_Mins_arriv,
        Arrive_Variance_Mins_9_dep AS Arrive_Variance_Mins_dep,
        Arrive_Variance_Mins_9_arriv AS Arrive_Variance_Mins_arriv,
        Travel_Time_Mins_9_dep AS Travel_Time_Mins_dep,
        Travel_Time_Mins_9_arriv AS Travel_Time_Mins_arriv,
        Idle_Time_Mins_9_dep AS Idle_Time_Mins_dep,
        Idle_Time_Mins_9_arriv AS Idle_Time_Mins_arriv,
        KM_Distance_Event_9_dep AS KM_Distance_Event_dep,
        KM_Distance_Event_9_arriv AS KM_Distance_Event_arriv,
        KM_HR_Event_9_dep AS KM_HR_Event_dep,
        KM_HR_Event_9_arriv AS KM_HR_Event_arriv
    FROM public_ready_for_ML.data2_stations
),
data_station_10 AS (
    SELECT id_train,
        Station_Name_10_dep AS Station_Name_dep,
        Station_Name_10_arriv AS Station_Name_arriv,
        Plan_Timestamp_10_dep AS Plan_Timestamp_dep,
        Plan_Timestamp_10_arriv AS Plan_Timestamp_arriv,
        Actual_Timestamp_10_dep AS Actual_Timestamp_dep,
        Actual_Timestamp_10_arriv AS Actual_Timestamp_arriv,
        Time_From_Prior_Plan_Mins_10_dep AS Time_From_Prior_Plan_Mins_dep,
        Time_From_Prior_Plan_Mins_10_arriv AS Time_From_Prior_Plan_Mins_arriv,
        Depart_Variance_Mins_10_dep AS Depart_Variance_Mins_dep,
        Depart_Variance_Mins_10_arriv AS Depart_Variance_Mins_arriv,
        Arrive_Variance_Mins_10_dep AS Arrive_Variance_Mins_dep,
        Arrive_Variance_Mins_10_arriv AS Arrive_Variance_Mins_arriv,
        Travel_Time_Mins_10_dep AS Travel_Time_Mins_dep,
        Travel_Time_Mins_10_arriv AS Travel_Time_Mins_arriv,
        Idle_Time_Mins_10_dep AS Idle_Time_Mins_dep,
        Idle_Time_Mins_10_arriv AS Idle_Time_Mins_arriv,
        KM_Distance_Event_10_dep AS KM_Distance_Event_dep,
        KM_Distance_Event_10_arriv AS KM_Distance_Event_arriv,
        KM_HR_Event_10_dep AS KM_HR_Event_dep,
        KM_HR_Event_10_arriv AS KM_HR_Event_arriv
    FROM public_ready_for_ML.data2_stations
),
data_station_11 AS (
    SELECT id_train,
        Station_Name_11_dep AS Station_Name_dep,
        Station_Name_11_arriv AS Station_Name_arriv,
        Plan_Timestamp_11_dep AS Plan_Timestamp_dep,
        Plan_Timestamp_11_arriv AS Plan_Timestamp_arriv,
        Actual_Timestamp_11_dep AS Actual_Timestamp_dep,
        Actual_Timestamp_11_arriv AS Actual_Timestamp_arriv,
        Time_From_Prior_Plan_Mins_11_dep AS Time_From_Prior_Plan_Mins_dep,
        Time_From_Prior_Plan_Mins_11_arriv AS Time_From_Prior_Plan_Mins_arriv,
        Depart_Variance_Mins_11_dep AS Depart_Variance_Mins_dep,
        Depart_Variance_Mins_11_arriv AS Depart_Variance_Mins_arriv,
        Arrive_Variance_Mins_11_dep AS Arrive_Variance_Mins_dep,
        Arrive_Variance_Mins_11_arriv AS Arrive_Variance_Mins_arriv,
        Travel_Time_Mins_11_dep AS Travel_Time_Mins_dep,
        Travel_Time_Mins_11_arriv AS Travel_Time_Mins_arriv,
        Idle_Time_Mins_11_dep AS Idle_Time_Mins_dep,
        Idle_Time_Mins_11_arriv AS Idle_Time_Mins_arriv,
        KM_Distance_Event_11_dep AS KM_Distance_Event_dep,
        KM_Distance_Event_11_arriv AS KM_Distance_Event_arriv,
        KM_HR_Event_11_dep AS KM_HR_Event_dep,
        KM_HR_Event_11_arriv AS KM_HR_Event_arriv
    FROM public_ready_for_ML.data2_stations
),
data_station_12 AS (
    SELECT id_train,
        Station_Name_12_dep AS Station_Name_dep,
        Station_Name_12_arriv AS Station_Name_arriv,
        Plan_Timestamp_12_dep AS Plan_Timestamp_dep,
        Plan_Timestamp_12_arriv AS Plan_Timestamp_arriv,
        Actual_Timestamp_12_dep AS Actual_Timestamp_dep,
        Actual_Timestamp_12_arriv AS Actual_Timestamp_arriv,
        Time_From_Prior_Plan_Mins_12_dep AS Time_From_Prior_Plan_Mins_dep,
        Time_From_Prior_Plan_Mins_12_arriv AS Time_From_Prior_Plan_Mins_arriv,
        Depart_Variance_Mins_12_dep AS Depart_Variance_Mins_dep,
        Depart_Variance_Mins_12_arriv AS Depart_Variance_Mins_arriv,
        Arrive_Variance_Mins_12_dep AS Arrive_Variance_Mins_dep,
        Arrive_Variance_Mins_12_arriv AS Arrive_Variance_Mins_arriv,
        Travel_Time_Mins_12_dep AS Travel_Time_Mins_dep,
        Travel_Time_Mins_12_arriv AS Travel_Time_Mins_arriv,
        Idle_Time_Mins_12_dep AS Idle_Time_Mins_dep,
        Idle_Time_Mins_12_arriv AS Idle_Time_Mins_arriv,
        KM_Distance_Event_12_dep AS KM_Distance_Event_dep,
        KM_Distance_Event_12_arriv AS KM_Distance_Event_arriv,
        KM_HR_Event_12_dep AS KM_HR_Event_dep,
        KM_HR_Event_12_arriv AS KM_HR_Event_arriv
    FROM public_ready_for_ML.data2_stations
),
union_of_data_station AS (
    SELECT *
    FROM data_station_1
    UNION ALL
    SELECT *
    FROM data_station_2
    UNION ALL
    SELECT *
    FROM data_station_3
    UNION ALL
    SELECT *
    FROM data_station_4
    UNION ALL
    SELECT *
    FROM data_station_5
    UNION ALL
    SELECT *
    FROM data_station_6
    UNION ALL
    SELECT *
    FROM data_station_7
    UNION ALL
    SELECT *
    FROM data_station_8
    UNION ALL
    SELECT *
    FROM data_station_9
    UNION ALL
    SELECT *
    FROM data_station_10
    UNION ALL
    SELECT *
    FROM data_station_11
    UNION ALL
    SELECT *
    FROM data_station_12
)
SELECT public_ready_for_ML.data1_trains_wagons.*,
    Station_Name_dep,
    Station_Name_arriv,
    Plan_Timestamp_dep,
    Plan_Timestamp_arriv,
    Actual_Timestamp_dep,
    Actual_Timestamp_arriv,
    Time_From_Prior_Plan_Mins_dep,
    Time_From_Prior_Plan_Mins_arriv,
    Depart_Variance_Mins_dep,
    Depart_Variance_Mins_arriv,
    Arrive_Variance_Mins_dep,
    Arrive_Variance_Mins_arriv,
    Travel_Time_Mins_dep,
    Travel_Time_Mins_arriv,
    Idle_Time_Mins_dep,
    Idle_Time_Mins_arriv,
    KM_Distance_Event_dep,
    KM_Distance_Event_arriv,
    KM_HR_Event_dep,
    KM_HR_Event_arriv
FROM public_ready_for_ML.data1_trains_wagons
    LEFT JOIN union_of_data_station ON public_ready_for_ML.data1_trains_wagons.id_train = union_of_data_station.id_train
WHERE Station_Name_dep IS NOT NULL;
--------------
SELECT id_train,
Origin_Station_Name
FROM public_ready_for_ML.df_final_for_ml
WHERE id_train = 21165