DROP TABLE IF EXISTS {{ params.table_name }};
CREATE TABLE IF NOT EXISTS {{ params.table_name }} (
    id SERIAL PRIMARY KEY,
    STATION VARCHAR NOT NULL,
    COUNTRY VARCHAR NOT NULL,
    LAT FLOAT NOT NULL,
    LONG FLOAT NOT NULL
);