DROP TABLE IF EXISTS {{ params.table_name }};
CREATE TABLE IF NOT EXISTS {{ params.table_name }} (
    id SERIAL PRIMARY KEY,
    IDWAGON VARCHAR NOT NULL,
    Code_wagon VARCHAR NOT NULL,
    IDGARE_actuelle VARCHAR NOT NULL,
    Frein_regime VARCHAR NOT NULL,
    Tare VARCHAR NOT NULL,
    ID_Proprietaire VARCHAR NOT NULL,
    ID_Detenteur VARCHAR NOT NULL,
    ID_AyantDroit VARCHAR NOT NULL,
    ID_Maintenance VARCHAR NOT NULL,
    Serie VARCHAR NOT NULL,
    Aptitude_circulation VARCHAR NOT NULL,
    km_initial VARCHAR NOT NULL,
    Enr_actif VARCHAR NOT NULL,
    IDUtilisateur_creation VARCHAR NOT NULL,
    DateH_creation VARCHAR NOT NULL,
    IDUtilisateur_maj VARCHAR NOT NULL,
    DateH_maj VARCHAR NOT NULL,
    IDWAGON_MODELE VARCHAR NOT NULL,
    Date_mise_circulation VARCHAR NOT NULL,
    Voie_num VARCHAR NOT NULL,
    Circulation_statut VARCHAR NOT NULL,
    Etat_wagon VARCHAR NOT NULL,
    Commentaire VARCHAR NOT NULL,
    Capteur_num VARCHAR NOT NULL,
    Date_sortie_parc VARCHAR NOT NULL,
    Capacite VARCHAR NOT NULL,
    km_actuel VARCHAR NOT NULL,
    IDFOURNISSEUR_CONTRAT VARCHAR NOT NULL,
    Date_restitution VARCHAR NOT NULL,
    Wagon_client VARCHAR NOT NULL,
    Application_GPS VARCHAR NOT NULL,
    Top_GPS_HS VARCHAR NOT NULL,
    GPS_performance VARCHAR NOT NULL
);