DROP TABLE IF EXISTS {{ params.table_name }};
CREATE TABLE IF NOT EXISTS {{ params.table_name }} (
    id SERIAL PRIMARY KEY,
    IDTRAIN_JALON VARCHAR NOT NULL,
    Jalon_num VARCHAR NOT NULL,
    Lieu VARCHAR NOT NULL,
    DHR_Arrivee VARCHAR NOT NULL,
    DHT_Arrivee VARCHAR NOT NULL,
    DHT_Depart VARCHAR NOT NULL,
    DHR_Depart VARCHAR NOT NULL,
    IDTRAIN VARCHAR NOT NULL,
    IDGARE VARCHAR NOT NULL,
    Code_pays VARCHAR NOT NULL,
    Latitude VARCHAR NOT NULL,
    Longitude VARCHAR NOT NULL,
    Jalon_passage VARCHAR NOT NULL,
    H_Depart_ecart VARCHAR NOT NULL,
    H_Arrivee_ecart VARCHAR NOT NULL,
    IDUtilisateur_creation VARCHAR NOT NULL,
    DateH_creation VARCHAR NOT NULL,
    IDUtilisateur_maj VARCHAR NOT NULL,
    DateH_maj VARCHAR NOT NULL,
    Commentaire VARCHAR NOT NULL,
    Distance_origine VARCHAR NOT NULL,
    H_Arrivee_ecart1 VARCHAR NOT NULL,
    H_Arrivee_ecart2 VARCHAR NOT NULL,
    H_Depart_ecart1 VARCHAR NOT NULL,
    H_Depart_ecart2 VARCHAR NOT NULL,
    DHO_Depart VARCHAR NOT NULL,
    DHO_Arrivee VARCHAR NOT NULL
);