DROP TABLE IF EXISTS {{ params.table_name }};
CREATE TABLE IF NOT EXISTS {{ params.table_name }} (
    id SERIAL PRIMARY KEY,
    IDINCIDENT_CONCERNE VARCHAR NOT NULL,
    IDINCIDENT VARCHAR NOT NULL,
    IDTRAIN_UTI VARCHAR NOT NULL,
    IDTRAIN_WAGON VARCHAR NOT NULL,
    IDUtilisateur_creation VARCHAR NOT NULL,
    DateH_creation VARCHAR NOT NULL,
    IDUtilisateur_maj VARCHAR NOT NULL,
    DateH_maj VARCHAR NOT NULL,
    Unite VARCHAR NOT NULL,
    IDCOMMANDE_UTI VARCHAR NOT NULL,
    IDAGRES VARCHAR NOT NULL,
    IDFACTURE VARCHAR NOT NULL,
    IDTRAIN_LOT VARCHAR NOT NULL,
    IDWAGON VARCHAR NOT NULL,
    Annule_TrainLot VARCHAR NOT NULL,
    IDSOCIETE VARCHAR NOT NULL,
    IDFACTURE_FOUR VARCHAR NOT NULL
);